version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: blog_wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wpblog
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
    volumes:
      - wordpress_data:/var/www/html
    restart: always

  db:
    image: mysql:5.7
    container_name: blog_db
    environment:
      MYSQL_DATABASE: wpblog
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: blog_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    restart: always

volumes:
  wordpress_data:
  db_data:

